ARG BASE=hadoop-base
FROM ${BASE}

FROM docker.io/bitnami/spark:3.5

# COPY --from=hadoop-base /usr/local/hadoop/lib/native/libhdfs.so /opt/bitnami/common/lib/
# COPY --from=hadoop-base /usr/local/hadoop/lib/native/libhdfs.so.0.0.0 /opt/bitnami/common/lib/
